read:
	g++ --std=c++11 read_graycode.cpp -o read_graycode -lopencv_structured_light -lopencv_core -lopencv_highgui -lopencv_imgproc -lopencv_imgcodecs -lopencv_video -lopencv_videoio

create:
	g++ --std=c++11 create_map.cpp -o create_map -lopencv_structured_light -lopencv_core -lopencv_highgui -lopencv_imgproc -lopencv_imgcodecs -lopencv_video -lopencv_videoio

match:
	g++ --std=c++11 -O3 -fopenmp match_map.cpp -o match_map
